services:
  app:
    build: .
    ports:
      - "3000:3000"  # REST API
      - "5000:5000"  # gRPC
    networks:
      - proyectos-network
    environment:
      - PROJECTS_SERVICE_URL=proyectos-service:5001
      - AGENCIES_SERVICE_URL=agencias-service:5002
      - AGENCY_PROJECTS_SERVICE_URL=agencies-users-management-service:5003
      - EMPRESAS_SERVICE_URL=empresas-service:5004
      - PROYECTOS_INMOBILIARIOS_SERVICE_URL=proyectos-inmobiliarios:5005
      - TIPO_DOCUMENTO_SERVICE_URL=tipo-documento-service:5007
      - PERSONAS_SERVICE_URL=personas-service:5014
    extra_hosts:
      - "proyectos-service:host-gateway"
      - "agencias-service:host-gateway"
      - "agencies-users-management-service:host-gateway"
      - "empresas-service:host-gateway"
      - "proyectos-inmobiliarios:host-gateway"
      - "tipo-documento-service:host-gateway"
      - "personas-service:host-gateway"
 
networks:
  proyectos-network:
    name: inmobiliaria-network
    external: true