services:
  app:
    build: .
    ports:
      - "3900:3900"  # REST API
      - "5900:5900"  # gRPC
    networks:
      - proyectos-network
    environment:
      - PROJECTS_SERVICE_URL=proyectos-service:5001
      - AGENCIES_SERVICE_URL=agencias-service:5002
      - AGENCY_PROJECTS_SERVICE_URL=agencies-users-management-service:5003
      - EMPRESAS_SERVICE_URL=empresas-service:5004
      - PROYECTOS_INMOBILIARIOS_SERVICE_URL=proyectos-inmobiliarios:5005
      - TIPO_DOCUMENTO_SERVICE_URL=tipo-documento-service:5007
      - PERSONAS_SERVICE_URL=personas-service:5014
      - USUARIOS_SERVICE_URL=usuarios-service:5021
      - OPCIONES_SERVICE_URL=opciones-service:5022
      - ROLES_SERVICE_URL=roles-service:5020
      - UERS_SERVICE_URL=uers-service:5023
      - CLIENTES_SERVICE_URL=clientes-service:5026
      - MEDIO_CONTACTO_SERVICE_URL=medio-contacto-service:5031
    extra_hosts:
      - "proyectos-service:host-gateway"
      - "agencias-service:host-gateway"
      - "agencies-users-management-service:host-gateway"
      - "empresas-service:host-gateway"
      - "proyectos-inmobiliarios:host-gateway"
      - "tipo-documento-service:host-gateway"
      - "personas-service:host-gateway"
      - "usuarios-service:host-gateway"
      - "opciones-service:host-gateway"
      - "roles-service:host-gateway"
      - "uers-service:host-gateway"
      - "clientes-service:host-gateway"
      - "medio-contacto-service:host-gateway"
networks:
  proyectos-network:
    name: inmobiliaria-network
    external: true