services:
  app:
    build: .
    ports:
      - "3000:3000"  # REST API
      - "5000:5000"  # gRPC
    networks:
      - proyectos-network
    environment:
      - PROJECTS_SERVICE_URL=project-management-microservice:5001
      - AGENCIES_SERVICE_URL=agencies-management-microservice:5002
      - AGENCY_PROJECTS_SERVICE_URL=agencies-users-management-microservices:5003
    extra_hosts:
      - "project-management-microservice:host-gateway"
      - "agencies-management-microservice:host-gateway"
      - "agencies-users-management-microservices:host-gateway"
 
networks:
  proyectos-network:
    name: inmobiliaria-network
    external: true